### ISSUE TITLE
Traceback 

### ISSUE THREAD

**Issue by BhuttoJani** [d8rkmind/Pylookup#1]
Traceback (most recent call last):
  File "/home/kali/Desktop/Tools/Pyosint/pyosint.py", line 8, in <module>
    import resources.enumsub as subdom
  File "/home/kali/Desktop/Tools/Pyosint/resources/enumsub.py", line 15, in <module>
    import dns.resolver
  File "/home/kali/.local/lib/python3.11/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/home/kali/.local/lib/python3.11/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/home/kali/.local/lib/python3.11/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/home/kali/.local/lib/python3.11/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/home/kali/.local/lib/python3.11/site-packages/dns/query.py", line 63, in <module>
    import httpcore
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 13, in <module>
    from .http11 import HTTP11Connection
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 44, in <module>
    class HTTP11Connection(ConnectionInterface):
  File "/home/kali/.local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 140, in HTTP11Connection
    self, event: h11.Event, timeout: Optional[float] = None
                 ^^^^^^^^^
AttributeError: module 'h11' has no attribute 'Event'. Did you mean: '_events'?

**Comment by syamsv** [comment]
It looks like you're facing a compatibility problem between h11 and httpcore. The project was initially built on Python 3.9.

Considering the lack of recent development, it might be worth exploring alternative projects or solutions that are actively maintained and supported in the current environment.
